import React, { useState, useEffect, useCallback, useMemo, useRef } from 'react'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_ANON_KEY)
const UserRole = { ADMIN: 'ADMIN', OPERATOR: 'OPERATOR' }
const TxType = { BUY: 'BUY', SELL: 'SELL' }
const REGISTER_CODE = 'Yzz871127'
const MAX_ATT = 10, MAX_SIZE = 200*1024*1024
const fmt = v => new Intl.NumberFormat('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:4}).format(v)
const fmtDate = iso => new Date(iso).toLocaleString('zh-CN',{hour12:false,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'})
const getWeekKey = d => {const dt=new Date(d.getTime());dt.setHours(0,0,0,0);dt.setDate(dt.getDate()+3-((dt.getDay()+6)%7));const w1=new Date(dt.getFullYear(),0,4);const wn=1+Math.round(((dt.getTime()-w1.getTime())/864e5-3+((w1.getDay()+6)%7))/7);return`${dt.getFullYear()}-W${String(wn).padStart(2,'0')}`}
const localISO = d => new Date(d.getTime()-d.getTimezoneOffset()*6e4).toISOString().slice(0,19)
const genId = () => Date.now().toString(36)+Math.random().toString(36).slice(2,7)
const today = () => new Date().toISOString().split('T')[0]
const fileType = n => {const e=n.split('.').pop().toLowerCase();if(['jpg','jpeg','png','gif','webp','heic','heif','bmp'].includes(e))return'image';if(['mp4','mov','avi','mkv','webm','3gp','m4v'].includes(e))return'video';if(['mp3','wav','m4a','aac','ogg','amr','flac','wma'].includes(e))return'audio';return'other'}
const EP = {client_name:'',wechat:'',alipay:'',phone:'',okx_uid:'',gender:'',age:''}

const db = {
  async getUsers(){const{data,error}=await supabase.from('users').select('*').order('created_at',{ascending:true});if(error)throw error;return data||[]},
  async registerUser(u){const{data,error}=await supabase.from('users').insert([u]).select().single();if(error)throw error;return data},
  async loginUser(un,pw){const{data}=await supabase.from('users').select('*').eq('username',un).eq('password_hash',pw).single();return data},
  async getLedgers(){const{data,error}=await supabase.from('ledgers').select('*').order('created_at',{ascending:false});if(error)throw error;return data||[]},
  async createLedger(l){const{data,error}=await supabase.from('ledgers').insert([l]).select().single();if(error)throw error;return data},
  async deleteLedger(id){await supabase.from('transactions').delete().eq('ledger_id',id);await supabase.from('attachments').delete().eq('ledger_id',id);const{error}=await supabase.from('ledgers').delete().eq('id',id);if(error)throw error},
  async getTx(lid){const{data,error}=await supabase.from('transactions').select('*').eq('ledger_id',lid).order('timestamp',{ascending:false});if(error)throw error;return data||[]},
  async addTx(tx){const{data,error}=await supabase.from('transactions').insert([tx]).select().single();if(error)throw error;return data},
  async updateTx(id,u){const{data,error}=await supabase.from('transactions').update(u).eq('id',id).select().single();if(error)throw error;return data},
  async deleteTx(id){await supabase.from('attachments').delete().eq('transaction_id',id);const{error}=await supabase.from('transactions').delete().eq('id',id);if(error)throw error},
  async deleteAllTx(lid){await supabase.from('attachments').delete().eq('ledger_id',lid);const{error}=await supabase.from('transactions').delete().eq('ledger_id',lid);if(error)throw error},
  async getAllAtt(lid){const{data,error}=await supabase.from('attachments').select('*').eq('ledger_id',lid).order('created_at',{ascending:true});if(error)throw error;return data||[]},
  async addAtt(a){const{data,error}=await supabase.from('attachments').insert([a]).select().single();if(error)throw error;return data},
  async delAtt(att){await supabase.storage.from('evidence').remove([att.storage_path]);const{error}=await supabase.from('attachments').delete().eq('id',att.id);if(error)throw error},
  async upload(file,txId,lid){const p=`${lid}/${txId}/${genId()}.${file.name.split('.').pop()}`;const{error}=await supabase.storage.from('evidence').upload(p,file,{cacheControl:'3600',upsert:false});if(error)throw error;const{data:u}=supabase.storage.from('evidence').getPublicUrl(p);return{storage_path:p,public_url:u.publicUrl,file_name:file.name,file_size:file.size,file_type:fileType(file.name)}},
  subTx(lid,cb){const ch=supabase.channel(`tx-${lid}`).on('postgres_changes',{event:'*',schema:'public',table:'transactions',filter:`ledger_id=eq.${lid}`},()=>db.getTx(lid).then(cb)).subscribe();return()=>supabase.removeChannel(ch)},
  subUsers(cb){const ch=supabase.channel('u-rt').on('postgres_changes',{event:'*',schema:'public',table:'users'},()=>db.getUsers().then(cb)).subscribe();return()=>supabase.removeChannel(ch)},
  subLedgers(cb){const ch=supabase.channel('l-rt').on('postgres_changes',{event:'*',schema:'public',table:'ledgers'},()=>db.getLedgers().then(cb)).subscribe();return()=>supabase.removeChannel(ch)}
}

// === 小组件 ===
const Toast=({message,type,onClose})=>{useEffect(()=>{const t=setTimeout(onClose,2800);return()=>clearTimeout(t)},[onClose]);const c={success:'from-emerald-500 to-teal-600',error:'from-red-500 to-rose-600',info:'from-sky-500 to-blue-600',warning:'from-amber-500 to-orange-600'};return<div className="fixed top-6 right-6 z-[9999] animate-slide-in"><div className={`bg-gradient-to-r ${c[type]||c.info} text-white px-5 py-3 rounded-2xl shadow-2xl flex items-center gap-3 min-w-[260px]`}><span className="text-sm font-medium">{message}</span></div></div>}
const Confirm=({title,message,onConfirm,onCancel})=>(<div className="fixed inset-0 z-[9998] flex items-center justify-center" style={{backdropFilter:'blur(8px)',background:'rgba(0,0,0,0.4)'}}><div className="bg-white rounded-3xl p-8 max-w-sm w-full mx-4 shadow-2xl" style={{animation:'scaleIn 0.2s ease-out'}}><div className="text-center"><div className="w-16 h-16 mx-auto mb-4 rounded-full bg-red-50 flex items-center justify-center"><span className="text-3xl">⚠️</span></div><h3 className="text-xl font-bold text-gray-900 mb-2">{title}</h3><p className="text-gray-500 text-sm mb-8">{message}</p></div><div className="flex gap-3"><button onClick={onCancel} className="flex-1 py-3 rounded-2xl border-2 border-gray-200 text-gray-600 font-semibold hover:bg-gray-50">取消</button><button onClick={onConfirm} className="flex-1 py-3 rounded-2xl bg-red-500 text-white font-semibold hover:bg-red-600 shadow-lg shadow-red-200">确认</button></div></div></div>)
const EyeO=()=><svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/></svg>
const EyeC=()=><svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M3 3l18 18"/></svg>

// === 附件预览 ===
const Viewer=({atts,idx:initIdx,onClose})=>{const[idx,setIdx]=useState(initIdx||0);const a=atts[idx];if(!a)return null;return(<div className="fixed inset-0 z-[9997] flex items-center justify-center" style={{backdropFilter:'blur(12px)',background:'rgba(0,0,0,0.7)'}} onClick={onClose}><div className="relative max-w-4xl w-full max-h-[90vh] mx-4" onClick={e=>e.stopPropagation()}><div className="absolute top-2 right-2 z-10 flex gap-2"><a href={a.public_url} download={a.file_name} target="_blank" rel="noreferrer" className="w-10 h-10 rounded-xl bg-white/20 hover:bg-white/30 flex items-center justify-center text-white">⬇</a><button onClick={onClose} className="w-10 h-10 rounded-xl bg-white/20 hover:bg-white/30 flex items-center justify-center text-white">✕</button></div>{atts.length>1&&<><button onClick={()=>setIdx(i=>(i-1+atts.length)%atts.length)} className="absolute left-2 top-1/2 -translate-y-1/2 z-10 w-10 h-10 rounded-xl bg-white/20 hover:bg-white/30 text-white text-xl flex items-center justify-center">‹</button><button onClick={()=>setIdx(i=>(i+1)%atts.length)} className="absolute right-2 top-1/2 -translate-y-1/2 z-10 w-10 h-10 rounded-xl bg-white/20 hover:bg-white/30 text-white text-xl flex items-center justify-center">›</button></>}<div className="flex items-center justify-center min-h-[60vh]">{a.file_type==='image'&&<img src={a.public_url} alt="" className="max-w-full max-h-[80vh] rounded-2xl object-contain"/>}{a.file_type==='video'&&<video src={a.public_url} controls className="max-w-full max-h-[80vh] rounded-2xl"/>}{a.file_type==='audio'&&<div className="bg-white/10 rounded-3xl p-8 text-center"><div className="text-6xl mb-4">🎵</div><p className="text-white/80 text-sm mb-4">{a.file_name}</p><audio src={a.public_url} controls className="w-full"/></div>}{a.file_type==='other'&&<div className="bg-white/10 rounded-3xl p-8 text-center"><div className="text-6xl mb-4">📄</div><p className="text-white/80 text-sm">{a.file_name}</p></div>}</div><div className="text-center mt-3 text-white/60 text-xs">{idx+1}/{atts.length} · {a.file_name}</div></div></div>)}

// === 附件面板 ===
const AttPanel=({txId,lid,atts,setAtts,toast:showT,ro})=>{const[upl,setUpl]=useState(false);const[vi,setVi]=useState(null);const fr=useRef(null);const up=async e=>{const fs=Array.from(e.target.files||[]);if(!fs.length)return;if(atts.length+fs.length>MAX_ATT){showT(`最多${MAX_ATT}个`,'warning');return};for(const f of fs){if(f.size>MAX_SIZE){showT(`${f.name}超200MB`,'error');return}};setUpl(true);try{for(const f of fs){const info=await db.upload(f,txId,lid);const att=await db.addAtt({id:genId(),transaction_id:txId,ledger_id:lid,...info,created_at:new Date().toISOString()});setAtts(p=>[...p,att])};showT(`${fs.length}个文件已上传`,'success')}catch{showT('上传失败','error')};setUpl(false);if(fr.current)fr.current.value=''};const ic={image:'🖼️',video:'🎬',audio:'🎵',other:'📄'};return(<div className="mt-2">{vi!==null&&<Viewer atts={atts} idx={vi} onClose={()=>setVi(null)}/>}{atts.length>0&&<div className="flex flex-wrap gap-2 mb-2">{atts.map((a,i)=><div key={a.id} className="relative group"><button onClick={()=>setVi(i)} className="w-14 h-14 rounded-xl border border-gray-200 overflow-hidden flex items-center justify-center bg-gray-50 hover:border-sky-300" title={a.file_name}>{a.file_type==='image'?<img src={a.public_url} alt="" className="w-full h-full object-cover"/>:<span className="text-xl">{ic[a.file_type]}</span>}</button>{!ro&&<button onClick={async()=>{try{await db.delAtt(a);setAtts(p=>p.filter(x=>x.id!==a.id));showT('已删除','success')}catch{showT('失败','error')}}} className="absolute -top-1.5 -right-1.5 w-5 h-5 rounded-full bg-red-500 text-white text-[10px] flex items-center justify-center opacity-0 group-hover:opacity-100 shadow">✕</button>}</div>)}</div>}{!ro&&atts.length<MAX_ATT&&<div><input ref={fr} type="file" multiple accept="image/*,video/*,audio/*,.mp4,.mov,.avi,.mp3,.wav,.m4a,.aac,.amr,.3gp,.m4v,.webm" onChange={up} className="hidden"/><button onClick={()=>fr.current?.click()} disabled={upl} className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-gray-50 hover:bg-gray-100 border border-dashed border-gray-300 rounded-xl text-xs text-gray-500 disabled:opacity-50">{upl?'上传中...':`📎 上传存证 (${atts.length}/${MAX_ATT})`}</button></div>}</div>)}

// === 客户资料卡 ===
const ProfileCard=({t})=>{if(!t.client_name)return null;const fs=[{l:'微信',v:t.wechat,i:'💬'},{l:'支付宝',v:t.alipay,i:'💰'},{l:'手机',v:t.phone,i:'📱'},{l:'欧易UID',v:t.okx_uid,i:'🔗'},{l:'性别',v:t.gender,i:'👤'},{l:'年龄',v:t.age,i:'🎂'}].filter(f=>f.v);return(<div className="bg-gradient-to-r from-slate-50 to-sky-50 rounded-xl p-3 border border-sky-100"><div className="flex items-center gap-2 mb-2"><span>👤</span><span className="font-bold text-gray-800 text-sm">{t.client_name}</span></div>{fs.length>0&&<div className="grid grid-cols-2 sm:grid-cols-3 gap-x-4 gap-y-1">{fs.map(f=><div key={f.l} className="flex items-center gap-1 text-[11px]"><span>{f.i}</span><span className="text-gray-400">{f.l}:</span><span className="text-gray-600 font-medium truncate">{f.v}</span></div>)}</div>}</div>)}

// === 登录 ===
const Login=({onRegister,users,onLogin})=>{const[mode,setMode]=useState('login');const[un,setUn]=useState('');const[pw,setPw]=useState('');const[rc,setRc]=useState('');const[role,setRole]=useState(UserRole.OPERATOR);const[err,setErr]=useState('');const[ld,setLd]=useState(false);const[sp,setSp]=useState(false);const[sr,setSr]=useState(false);const ac=users.filter(u=>u.role===UserRole.ADMIN).length;const oc=users.filter(u=>u.role===UserRole.OPERATOR).length
  const submit=async()=>{setErr('');if(!un.trim()||!pw.trim()){setErr('请填写完整');return};setLd(true);if(mode==='register'){if(!rc.trim()){setErr('请输入注册码');setLd(false);return};if(rc!==REGISTER_CODE){setErr('注册码错误');setLd(false);return};try{const ok=await onRegister(un.trim(),pw,role);if(ok){setMode('login');setPw('');setRc('');setUn('')}}catch(e){setErr(e.message||'注册失败')}}else{try{const ok=await onLogin(un.trim(),pw);if(!ok)setErr('用户名或密码错误')}catch(e){setErr(e.message||'登录失败')}};setLd(false)}
  const is={color:'#fff',backgroundColor:'rgba(255,255,255,0.08)',caretColor:'#38bdf8'}
  return(<div className="min-h-screen flex items-center justify-center px-4" style={{background:'linear-gradient(135deg,#0f172a 0%,#1e293b 40%,#0c4a6e 100%)'}}><div className="fixed inset-0 overflow-hidden pointer-events-none"><div className="absolute top-[-20%] right-[-10%] w-[600px] h-[600px] rounded-full" style={{background:'radial-gradient(circle,rgba(14,165,233,0.15) 0%,transparent 70%)'}}/></div><div className="relative w-full max-w-[420px]"><div className="text-center mb-10"><div className="inline-flex items-center justify-center w-20 h-20 rounded-3xl mb-5" style={{background:'linear-gradient(135deg,#0ea5e9,#6366f1)',boxShadow:'0 20px 60px rgba(14,165,233,0.3)'}}><span className="text-white text-3xl font-black">U₮</span></div><h1 className="text-3xl font-black text-white">USDT 管理系统</h1><p className="text-sky-300/60 mt-2 text-sm">进出货 · 财务追踪 · 智能报表</p></div>
  <div className="bg-white/[0.07] backdrop-blur-xl rounded-3xl p-8 border border-white/10" style={{boxShadow:'0 30px 80px rgba(0,0,0,0.3)'}}>
    <div className="flex bg-white/5 rounded-2xl p-1 mb-8">{['login','register'].map(k=><button key={k} onClick={()=>{setMode(k);setErr('')}} className={`flex-1 py-2.5 rounded-xl text-sm font-bold transition-all ${mode===k?'bg-white text-gray-900 shadow-lg':'text-white/50'}`}>{k==='login'?'登录':'注册'}</button>)}</div>
    <div className="space-y-5">
      <div><label className="block text-xs font-bold text-white/40 uppercase mb-2 ml-1">用户名</label><input type="text" value={un} onChange={e=>setUn(e.target.value)} style={is} className="w-full px-4 py-3.5 border border-white/10 rounded-2xl placeholder-white/25 outline-none focus:border-sky-400/50" placeholder="输入用户名" onKeyDown={e=>e.key==='Enter'&&submit()}/></div>
      <div><label className="block text-xs font-bold text-white/40 uppercase mb-2 ml-1">密码</label><div className="relative"><input type={sp?'text':'password'} value={pw} onChange={e=>setPw(e.target.value)} style={is} className="w-full px-4 py-3.5 pr-12 border border-white/10 rounded-2xl placeholder-white/25 outline-none focus:border-sky-400/50" placeholder="输入密码" onKeyDown={e=>e.key==='Enter'&&submit()}/><button type="button" onClick={()=>setSp(!sp)} className="absolute right-3 top-1/2 -translate-y-1/2 p-1.5 text-white/30 hover:text-white/70">{sp?<EyeO/>:<EyeC/>}</button></div></div>
      {mode==='register'&&<div><label className="block text-xs font-bold text-white/40 uppercase mb-2 ml-1">注册码</label><div className="relative"><input type={sr?'text':'password'} value={rc} onChange={e=>setRc(e.target.value)} style={is} className="w-full px-4 py-3.5 pr-12 border border-white/10 rounded-2xl placeholder-white/25 outline-none focus:border-sky-400/50" placeholder="注册码" onKeyDown={e=>e.key==='Enter'&&submit()}/><button type="button" onClick={()=>setSr(!sr)} className="absolute right-3 top-1/2 -translate-y-1/2 p-1.5 text-white/30 hover:text-white/70">{sr?<EyeO/>:<EyeC/>}</button></div></div>}
      {mode==='register'&&<div><label className="block text-xs font-bold text-white/40 uppercase mb-2 ml-1">类型</label><div className="grid grid-cols-2 gap-3">{[{r:UserRole.OPERATOR,l:'操作员',c:oc,m:2},{r:UserRole.ADMIN,l:'管理员',c:ac,m:1}].map(it=>{const full=it.c>=it.m;return<button key={it.r} disabled={full} onClick={()=>!full&&setRole(it.r)} className={`py-3 px-4 rounded-2xl border text-sm font-bold ${role===it.r&&!full?'border-sky-400/60 bg-sky-500/10 text-sky-300':'border-white/10 text-white/40'} ${full?'opacity-30 cursor-not-allowed':'cursor-pointer'}`}>{it.l}<span className="block text-[10px] mt-0.5 opacity-60">{it.c}/{it.m}{full?' 已满':''}</span></button>})}</div></div>}
      {err&&<div className="px-4 py-3 bg-red-500/10 border border-red-500/20 rounded-2xl"><span className="text-red-300 text-sm">{err}</span></div>}
      <button onClick={submit} disabled={ld} className="w-full py-4 rounded-2xl font-bold text-white disabled:opacity-60" style={{background:'linear-gradient(135deg,#0ea5e9,#6366f1)'}}>{ld?'处理中...':mode==='register'?'注册':'登录'}</button>
    </div>
  </div></div></div>)
}

// === 交易簿选择 ===
const LedgerSel=({ledgers,cu,onSelect,onCreate,toast:showT})=>{const[sc,setSc]=useState(false);const[nm,setNm]=useState('');const[pwd,setPwd]=useState('');const[ul,setUl]=useState(null);const[ip,setIp]=useState('');const isA=cu.role===UserRole.ADMIN
  const cr=async()=>{if(!nm.trim()||!pwd.trim()){showT('填写名称和密码','warning');return};try{await onCreate(nm.trim(),pwd);setSc(false);setNm('');setPwd('');showT('已创建','success')}catch{showT('失败','error')}}
  const unlock=l=>{if(ip===l.password_hash){onSelect(l);setIp('');setUl(null)}else showT('密码错误','error')}
  return(<div className="max-w-3xl mx-auto py-8 px-4"><div className="flex items-center justify-between mb-8"><div><h1 className="text-2xl font-extrabold text-gray-900">📒 交易簿</h1><p className="text-xs text-gray-400 mt-1">选择交易簿开始操作</p></div>{isA&&<button onClick={()=>setSc(true)} className="px-5 py-2.5 rounded-2xl font-bold text-white text-sm" style={{background:'linear-gradient(135deg,#0ea5e9,#6366f1)'}}>+ 新建</button>}</div>
    {sc&&<div className="fixed inset-0 z-[9998] flex items-center justify-center" style={{backdropFilter:'blur(8px)',background:'rgba(0,0,0,0.4)'}}><div className="bg-white rounded-3xl p-8 max-w-sm w-full mx-4 shadow-2xl" style={{animation:'scaleIn 0.2s ease-out'}}><h3 className="text-lg font-bold mb-6">📒 新建交易簿</h3><div className="space-y-4"><div><label className="block text-xs font-bold text-gray-400 uppercase mb-1.5">名称</label><input type="text" value={nm} onChange={e=>setNm(e.target.value)} className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-sky-200 text-sm" placeholder="如：2月记录"/></div><div><label className="block text-xs font-bold text-gray-400 uppercase mb-1.5">密码</label><input type="text" value={pwd} onChange={e=>setPwd(e.target.value)} className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-sky-200 text-sm" placeholder="设置密码"/></div></div><div className="flex gap-3 mt-6"><button onClick={()=>setSc(false)} className="flex-1 py-3 rounded-2xl border-2 border-gray-200 text-gray-600 font-semibold">取消</button><button onClick={cr} className="flex-1 py-3 rounded-2xl text-white font-semibold" style={{background:'linear-gradient(135deg,#0ea5e9,#6366f1)'}}>创建</button></div></div></div>}
    {ul&&<div className="fixed inset-0 z-[9998] flex items-center justify-center" style={{backdropFilter:'blur(8px)',background:'rgba(0,0,0,0.4)'}}><div className="bg-white rounded-3xl p-8 max-w-sm w-full mx-4 shadow-2xl" style={{animation:'scaleIn 0.2s ease-out'}}><div className="text-center mb-6"><span className="text-4xl">🔐</span><h3 className="text-lg font-bold mt-3">{ul.name}</h3><p className="text-gray-400 text-sm mt-1">请输入密码</p></div><input type="password" value={ip} onChange={e=>setIp(e.target.value)} onKeyDown={e=>e.key==='Enter'&&unlock(ul)} className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-sky-200 text-sm text-center tracking-widest mb-4" placeholder="密码" autoFocus/><div className="flex gap-3"><button onClick={()=>{setUl(null);setIp('')}} className="flex-1 py-3 rounded-2xl border-2 border-gray-200 text-gray-600 font-semibold">取消</button><button onClick={()=>unlock(ul)} className="flex-1 py-3 rounded-2xl text-white font-semibold" style={{background:'linear-gradient(135deg,#0ea5e9,#6366f1)'}}>解锁</button></div></div></div>}
    {ledgers.length===0?<div className="text-center py-20 text-gray-300"><span className="text-6xl block mb-4">📒</span><p className="text-sm">暂无交易簿</p></div>:<div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{ledgers.map((l,i)=><button key={l.id} onClick={()=>{setUl(l);setIp('')}} className="bg-white p-6 rounded-2xl border border-gray-100 hover:border-sky-200 hover:shadow-lg transition-all text-left group" style={{animation:`fadeUp 0.4s ease-out ${i*0.06}s both`}}><div className="flex items-start justify-between"><div><h3 className="text-lg font-bold text-gray-900 group-hover:text-sky-600">{l.name}</h3><p className="text-xs text-gray-400 mt-1">创建: {l.created_by}</p><p className="text-xs text-gray-300 mt-0.5">{new Date(l.created_at).toLocaleDateString('zh-CN')}</p></div><span className="text-2xl text-gray-200 group-hover:text-sky-400">🔐</span></div></button>)}</div>}
  </div>)
}

// === 主应用 ===
export default function App(){
  const[ready,setReady]=useState(false)
  const[cu,setCu]=useState(()=>{try{return JSON.parse(sessionStorage.getItem('usdt_user'))}catch{return null}})
  const[users,setUsers]=useState([]);const[ledgers,setLedgers]=useState([]);const[aLedger,setALedger]=useState(null)
  const[txs,setTxs]=useState([]);const[allAtt,setAllAtt]=useState([])
  const[tab,setTab]=useState('daily');const[selDate,setSelDate]=useState(today())
  const[toast,setToast]=useState(null);const[cfm,setCfm]=useState(null);const[sync,setSync]=useState(false)
  const[fd,setFd]=useState({price:'',quantity:'',type:TxType.BUY,datetime:localISO(new Date())})
  const[editId,setEditId]=useState(null)
  const[prof,setProf]=useState({...EP});const[showProf,setShowProf]=useState(false)
  const[pFiles,setPFiles]=useState([]);const[txAtt,setTxAtt]=useState({});const[expTx,setExpTx]=useState(null)
  const pfRef=useRef(null)
  const sT=useCallback((m,t='info')=>setToast({message:m,type:t,key:Date.now()}),[])
  useEffect(()=>{if(cu)sessionStorage.setItem('usdt_user',JSON.stringify(cu));else sessionStorage.removeItem('usdt_user')},[cu])
  useEffect(()=>{let u1,u2;(async()=>{try{const[u,l]=await Promise.all([db.getUsers(),db.getLedgers()]);setUsers(u);setLedgers(l);u1=db.subUsers(u=>setUsers(u));u2=db.subLedgers(l=>setLedgers(l))}catch(e){console.error(e)};setReady(true)})();return()=>{u1?.();u2?.()}},[])
  useEffect(()=>{if(!aLedger){setTxs([]);setAllAtt([]);return};let u;(async()=>{const[t,a]=await Promise.all([db.getTx(aLedger.id),db.getAllAtt(aLedger.id)]);setTxs(t);setAllAtt(a);u=db.subTx(aLedger.id,t=>setTxs(t))})();return()=>{u?.()}},[aLedger])
  useEffect(()=>{const m={};allAtt.forEach(a=>{if(!m[a.transaction_id])m[a.transaction_id]=[];m[a.transaction_id].push(a)});setTxAtt(m)},[allAtt])
  useEffect(()=>{if(!editId){const n=new Date();const[y,m,d]=selDate.split('-').map(Number);setFd(p=>({...p,datetime:localISO(new Date(y,m-1,d,n.getHours(),n.getMinutes(),n.getSeconds()))}))}},[selDate,editId])

  const reg=async(un,pw,role)=>{if(users.find(u=>u.username===un)){sT('用户名已存在','error');return false};if(role===UserRole.ADMIN&&users.filter(u=>u.role===UserRole.ADMIN).length>=1){sT('最多1个管理员','error');return false};if(role===UserRole.OPERATOR&&users.filter(u=>u.role===UserRole.OPERATOR).length>=2){sT('最多2个操作员','error');return false};try{await db.registerUser({username:un,password_hash:pw,role});sT('注册成功','success');return true}catch{sT('注册失败','error');return false}}
  const login=async(un,pw)=>{const u=await db.loginUser(un,pw);if(u){setCu(u);sT(`欢迎，${u.username}！`,'success');return true};return false}
  const mkLedger=async(name,pwd)=>{await db.createLedger({id:genId(),name,password_hash:pwd,created_by:cu.username,created_at:new Date().toISOString()})}

  const summary=useMemo(()=>{const s=[...txs].sort((a,b)=>new Date(a.timestamp).getTime()-new Date(b.timestamp).getTime());let tQ=0,tC=0;s.filter(t=>t.date_str<selDate).forEach(t=>{if(t.type===TxType.BUY){tC+=t.total;tQ+=t.quantity}else{const a=tQ>0?tC/tQ:0;tQ=Math.max(0,tQ-t.quantity);tC=tQ*a}});let dBQ=0,dBA=0,dSQ=0,dSA=0,dP=0;const dT=s.filter(t=>t.date_str===selDate);dT.forEach(t=>{if(t.type===TxType.BUY){dBQ+=t.quantity;dBA+=t.total;tQ+=t.quantity;tC+=t.total}else{const a=tQ>0?tC/tQ:0;dSQ+=t.quantity;dSA+=t.total;dP+=(t.price-a)*t.quantity;tQ=Math.max(0,tQ-t.quantity);tC=tQ*a}});return{dayBuyQty:dBQ,dayBuyAmt:dBA,daySellQty:dSQ,daySellAmt:dSA,closingBal:tQ,avgCost:tQ>0?tC/tQ:0,dayProfit:dP,dayTxs:dT}},[txs,selDate])

  const weeklyData=useMemo(()=>{const s=[...txs].sort((a,b)=>new Date(a.timestamp).getTime()-new Date(b.timestamp).getTime());const w=new Map();let cQ=0,cC=0;s.forEach(t=>{const wk=getWeekKey(new Date(t.timestamp));if(!w.has(wk))w.set(wk,{weekKey:wk,buyQty:0,buyAmt:0,sellQty:0,sellAmt:0,profit:0});const r=w.get(wk);if(t.type===TxType.BUY){r.buyQty+=t.quantity;r.buyAmt+=t.total;cQ+=t.quantity;cC+=t.total}else{const a=cQ>0?cC/cQ:0;r.sellQty+=t.quantity;r.sellAmt+=t.total;r.profit+=(t.price-a)*t.quantity;cQ=Math.max(0,cQ-t.quantity);cC=cQ*a}});return Array.from(w.values()).reverse()},[txs])

  const submitTx=async()=>{if(!fd.price||!fd.quantity){sT('请填写价格和数量','warning');return};const price=parseFloat(fd.price),qty=parseFloat(fd.quantity);if(isNaN(price)||isNaN(qty)||price<=0||qty<=0){sT('必须为正数','warning');return};const ts=new Date(fd.datetime).toISOString(),dp=fd.datetime.split('T')[0];setSync(true);try{if(editId){const tx=txs.find(t=>t.id===editId);const ec=cu?.role===UserRole.OPERATOR?(tx?.edit_count||0)+1:(tx?.edit_count||0);await db.updateTx(editId,{price,quantity:qty,total:price*qty,type:fd.type,timestamp:ts,date_str:dp,edit_count:ec,client_name:prof.client_name,wechat:prof.wechat,alipay:prof.alipay,phone:prof.phone,okx_uid:prof.okx_uid,gender:prof.gender,age:prof.age});setEditId(null);sT('已更新','success')}else{const txId=genId();await db.addTx({id:txId,price,quantity:qty,total:price*qty,type:fd.type,timestamp:ts,date_str:dp,edit_count:0,operator_name:cu?.username||'',ledger_id:aLedger.id,client_name:prof.client_name,wechat:prof.wechat,alipay:prof.alipay,phone:prof.phone,okx_uid:prof.okx_uid,gender:prof.gender,age:prof.age});if(pFiles.length>0){for(const f of pFiles){const info=await db.upload(f,txId,aLedger.id);await db.addAtt({id:genId(),transaction_id:txId,ledger_id:aLedger.id,...info,created_at:new Date().toISOString()})};setAllAtt(await db.getAllAtt(aLedger.id));setPFiles([])};sT(fd.type===TxType.BUY?'进货已添加':'出货已添加','success')}}catch(e){sT('失败: '+(e.message||''),'error')};setFd(p=>({...p,price:'',quantity:''}));setProf({...EP});setShowProf(false);setSync(false)}

  const startEdit=t=>{if(cu?.role===UserRole.OPERATOR&&t.edit_count>=1){sT('修改次数已达上限','warning');return};setEditId(t.id);setFd({price:String(t.price),quantity:String(t.quantity),type:t.type,datetime:localISO(new Date(t.timestamp))});setProf({client_name:t.client_name||'',wechat:t.wechat||'',alipay:t.alipay||'',phone:t.phone||'',okx_uid:t.okx_uid||'',gender:t.gender||'',age:t.age||''});if(t.client_name)setShowProf(true);sT('正在编辑','info')}
  const delTx=t=>{if(cu?.role!==UserRole.ADMIN)return;setCfm({title:'删除确认',message:'确定删除此记录及附件？',onConfirm:async()=>{setSync(true);try{await db.deleteTx(t.id);setAllAtt(await db.getAllAtt(aLedger.id));sT('已删除','success')}catch{sT('失败','error')};setSync(false);setCfm(null)},onCancel:()=>setCfm(null)})}
  const addPF=e=>{const fs=Array.from(e.target.files||[]);if(pFiles.length+fs.length>MAX_ATT){sT(`最多${MAX_ATT}个`,'warning');return};for(const f of fs){if(f.size>MAX_SIZE){sT(`${f.name}超200MB`,'error');return}};setPFiles(p=>[...p,...fs]);if(pfRef.current)pfRef.current.value=''}

  if(!ready)return<div className="min-h-screen flex items-center justify-center" style={{background:'#0f172a'}}><div className="text-center"><div className="w-12 h-12 mx-auto border-[3px] border-sky-400/30 border-t-sky-400 rounded-full" style={{animation:'spin 0.8s linear infinite'}}/><p className="text-sky-300/50 mt-4 text-sm">连接中...</p></div></div>
  if(!cu)return<><Login onRegister={reg} users={users} onLogin={login}/>{toast&&<Toast message={toast.message} type={toast.type} onClose={()=>setToast(null)}/>}</>

  const isA=cu.role===UserRole.ADMIN
  // 顶栏
  const NavBar=({children})=>(<header className="bg-white/80 backdrop-blur-xl border-b border-gray-100 sticky top-0 z-50" style={{boxShadow:'0 1px 20px rgba(0,0,0,0.04)'}}><div className="max-w-7xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between"><div className="flex items-center gap-4">{children}</div><div className="flex items-center gap-3"><div className="hidden sm:block text-right mr-1"><p className="text-[11px] text-gray-400">{isA?'管理员':'操作员'}</p><p className="text-sm font-bold text-gray-700">{cu.username}</p></div><button onClick={()=>setCu(null)} className="w-9 h-9 rounded-xl bg-gray-50 hover:bg-red-50 text-gray-400 hover:text-red-500 flex items-center justify-center"><svg className="w-[18px] h-[18px]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"/></svg></button></div></div></header>)
  const Logo=({onClick})=>(<button onClick={onClick} className="flex items-center gap-2 hover:opacity-70"><div className="w-9 h-9 rounded-xl flex items-center justify-center text-white font-black text-sm" style={{background:'linear-gradient(135deg,#0ea5e9,#6366f1)'}}>U₮</div><span className="font-extrabold text-lg text-gray-900 hidden sm:block">USDT-Tracker</span></button>)

  if(!aLedger)return(<div className="min-h-screen flex flex-col" style={{background:'#f8fafc'}}><NavBar><Logo onClick={()=>{}}/></NavBar><LedgerSel ledgers={ledgers} cu={cu} onSelect={setALedger} onCreate={mkLedger} toast={sT}/>{toast&&<Toast message={toast.message} type={toast.type} onClose={()=>setToast(null)}/>}</div>)

  const pvTotal=fd.price&&fd.quantity?parseFloat(fd.price)*parseFloat(fd.quantity):null
  const pI=(label,icon,key,ph,type='text')=><div><label className="block text-[10px] font-bold text-gray-400 uppercase mb-1">{icon} {label}</label><input type={type} value={prof[key]} onChange={e=>setProf(p=>({...p,[key]:e.target.value}))} className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg outline-none focus:ring-2 focus:ring-sky-200 text-sm" placeholder={ph}/></div>

  // === 渲染 ===
  return(<>
    {toast&&<Toast message={toast.message} type={toast.type} onClose={()=>setToast(null)}/>}
    {cfm&&<Confirm {...cfm}/>}
    <div className="min-h-screen flex flex-col" style={{background:'#f8fafc'}}>
      <NavBar>
        <Logo onClick={()=>setALedger(null)}/>
        <span className="hidden sm:inline text-gray-300">|</span><span className="text-sm font-bold text-sky-600 hidden sm:inline">📒 {aLedger.name}</span>
        {sync?<span className="hidden sm:inline-flex items-center gap-1 px-2 py-0.5 bg-sky-50 text-sky-500 rounded-lg text-[10px] font-bold"><span className="w-2 h-2 bg-sky-400 rounded-full" style={{animation:'spin 1s linear infinite'}}/>同步中</span>:<span className="hidden sm:inline-flex items-center gap-1 px-2 py-0.5 bg-emerald-50 text-emerald-500 rounded-lg text-[10px] font-bold"><span className="w-1.5 h-1.5 bg-emerald-400 rounded-full"/>已连接</span>}
        <nav className="hidden md:flex items-center gap-1">{[['daily','📊 每日记录'],['weekly','📈 报表'],['settings','⚙️ 设置']].map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`px-4 py-2 rounded-xl text-sm font-semibold transition-all ${tab===k?'bg-sky-50 text-sky-600':'text-gray-400 hover:text-gray-700'}`}>{l}</button>)}</nav>
      </NavBar>
      <nav className="md:hidden flex items-center justify-around border-b border-gray-100 py-1.5 bg-white">{[['daily','📊','每日'],['weekly','📈','报表'],['settings','⚙️','设置']].map(([k,ic,l])=><button key={k} onClick={()=>setTab(k)} className={`flex flex-col items-center gap-0.5 px-4 py-1.5 rounded-xl ${tab===k?'text-sky-600 bg-sky-50':'text-gray-400'}`}><span>{ic}</span><span className="text-[10px] font-bold">{l}</span></button>)}</nav>

      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 py-6">
        {tab==='daily'&&<div className="space-y-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div className="flex items-center gap-3"><input type="date" value={selDate} onChange={e=>setSelDate(e.target.value)} className="px-4 py-2.5 bg-white border border-gray-200 rounded-2xl shadow-sm outline-none font-semibold text-gray-700 text-sm"/><h1 className="text-xl font-extrabold text-gray-900">交易流水</h1></div>
            <div className="flex gap-2"><button onClick={()=>{const d=new Date(selDate);d.setDate(d.getDate()-1);setSelDate(d.toISOString().split('T')[0])}} className="px-3 py-2 bg-white border border-gray-200 rounded-xl text-gray-500 text-sm">←前一天</button><button onClick={()=>setSelDate(today())} className="px-3 py-2 bg-sky-50 border border-sky-200 rounded-xl text-sky-600 text-sm font-bold">今天</button><button onClick={()=>{const d=new Date(selDate);d.setDate(d.getDate()+1);setSelDate(d.toISOString().split('T')[0])}} className="px-3 py-2 bg-white border border-gray-200 rounded-xl text-gray-500 text-sm">后一天→</button></div>
          </div>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[{l:'当日进货',v:`${fmt(summary.dayBuyQty)} USDT`,s:`成本 ¥${fmt(summary.dayBuyAmt)}`,c:'text-sky-600',i:'📥'},{l:'当日出货',v:`${fmt(summary.daySellQty)} USDT`,s:`营收 ¥${fmt(summary.daySellAmt)}`,c:'text-amber-600',i:'📤'},{l:'当日利润',v:`¥${fmt(summary.dayProfit)}`,s:'加权平均成本',c:summary.dayProfit>=0?'text-emerald-600':'text-red-600',i:summary.dayProfit>=0?'📈':'📉'},{l:'当前仓位',v:`${fmt(summary.closingBal)} USDT`,s:`均价 ¥${fmt(summary.avgCost)}`,c:'text-violet-600',i:'💰',h:1}].map((c,i)=><div key={i} className={`bg-white p-4 rounded-2xl border hover:shadow-md ${c.h?'border-violet-200 ring-2 ring-violet-100':'border-gray-100'}`} style={{animation:`fadeUp 0.4s ease-out ${i*0.08}s both`}}><div className="flex items-start justify-between mb-2"><p className="text-[11px] font-bold text-gray-400 uppercase">{c.l}</p><span className="text-lg">{c.i}</span></div><p className={`text-xl font-extrabold ${c.c}`}>{c.v}</p><p className="text-[11px] text-gray-400 mt-1">{c.s}</p></div>)}</div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* 表单 */}
            <div className="lg:col-span-1"><div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm sticky top-28">
              <h3 className="text-base font-extrabold text-gray-900 mb-4 flex items-center gap-2"><span className="w-1.5 h-5 rounded-full" style={{background:editId?'linear-gradient(180deg,#f59e0b,#ef4444)':'linear-gradient(180deg,#0ea5e9,#6366f1)'}}/>{editId?'✏️ 编辑':'📝 新增'}</h3>
              <div className="space-y-3">
                <div className="grid grid-cols-2 gap-2 p-1 bg-gray-50 rounded-2xl">{[{t:TxType.BUY,l:'📥 进货',g:'linear-gradient(135deg,#0ea5e9,#0284c7)'},{t:TxType.SELL,l:'📤 出货',g:'linear-gradient(135deg,#f59e0b,#d97706)'}].map(b=><button key={b.t} onClick={()=>setFd(p=>({...p,type:b.t}))} className={`py-2 rounded-xl text-sm font-bold ${fd.type===b.t?'text-white shadow-lg':'text-gray-400'}`} style={fd.type===b.t?{background:b.g}:{}}>{b.l}</button>)}</div>
                <div className="grid grid-cols-2 gap-3"><div><label className="block text-[11px] font-bold text-gray-400 uppercase mb-1 ml-1">单价(¥)</label><input type="number" step="0.0001" value={fd.price} onChange={e=>setFd(p=>({...p,price:e.target.value}))} onKeyDown={e=>e.key==='Enter'&&submitTx()} className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-sky-200 text-sm" placeholder="7.25"/></div><div><label className="block text-[11px] font-bold text-gray-400 uppercase mb-1 ml-1">数量(USDT)</label><input type="number" step="0.01" value={fd.quantity} onChange={e=>setFd(p=>({...p,quantity:e.target.value}))} onKeyDown={e=>e.key==='Enter'&&submitTx()} className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-sky-200 text-sm" placeholder="1000"/></div></div>
                {pvTotal!==null&&!isNaN(pvTotal)&&pvTotal>0&&<div className="flex items-center justify-between px-4 py-2 bg-gray-50 rounded-xl border border-dashed border-gray-200"><span className="text-xs text-gray-400">预计金额</span><span className="text-base font-extrabold text-gray-700">¥{fmt(pvTotal)}</span></div>}
                <div><label className="block text-[11px] font-bold text-gray-400 uppercase mb-1 ml-1">交易时间</label><input type="datetime-local" step="1" value={fd.datetime} onChange={e=>setFd(p=>({...p,datetime:e.target.value}))} className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-sky-200 text-sm"/></div>

                {/* 客户资料+存证 可折叠 */}
                <div className="border border-gray-200 rounded-2xl overflow-hidden">
                  <button onClick={()=>setShowProf(!showProf)} className="w-full flex items-center justify-between px-4 py-3 bg-gradient-to-r from-slate-50 to-sky-50 hover:from-slate-100 hover:to-sky-100 transition-all"><span className="text-sm font-bold text-gray-700">👤 客户资料 & 📎 申诉存证</span><span className={`text-gray-400 text-xs transition-transform ${showProf?'rotate-180':''}`}>▼</span></button>
                  {showProf&&<div className="p-4 space-y-3 bg-white">
                    <div className="grid grid-cols-2 gap-3">
                      {pI('客户名称','👤','client_name','姓名/昵称')}
                      {pI('微信账号','💬','wechat','微信号')}
                      {pI('支付宝','💰','alipay','支付宝账号')}
                      {pI('手机号','📱','phone','手机号','tel')}
                      {pI('欧易UID','🔗','okx_uid','OKX UID')}
                      <div className="grid grid-cols-2 gap-2">
                        <div><label className="block text-[10px] font-bold text-gray-400 uppercase mb-1">👤 性别</label><select value={prof.gender} onChange={e=>setProf(p=>({...p,gender:e.target.value}))} className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg outline-none focus:ring-2 focus:ring-sky-200 text-sm"><option value="">未填</option><option value="男">男</option><option value="女">女</option></select></div>
                        {pI('年龄','🎂','age','年龄','number')}
                      </div>
                    </div>
                    {!editId&&<div className="pt-2 border-t border-gray-100">
                      <label className="block text-[10px] font-bold text-gray-400 uppercase mb-2">📎 申诉存证附件</label>
                      <input ref={pfRef} type="file" multiple accept="image/*,video/*,audio/*,.mp4,.mov,.avi,.mp3,.wav,.m4a,.aac,.amr,.3gp,.m4v,.webm" onChange={addPF} className="hidden"/>
                      {pFiles.length>0&&<div className="flex flex-wrap gap-1.5 mb-2">{pFiles.map((f,i)=><div key={i} className="relative group"><div className="w-12 h-12 rounded-lg bg-gray-100 flex items-center justify-center text-base border border-gray-200">{fileType(f.name)==='image'?'🖼️':fileType(f.name)==='video'?'🎬':'🎵'}</div><button onClick={()=>setPFiles(p=>p.filter((_,j)=>j!==i))} className="absolute -top-1 -right-1 w-4 h-4 rounded-full bg-red-500 text-white text-[9px] flex items-center justify-center opacity-0 group-hover:opacity-100">✕</button></div>)}</div>}
                      <button onClick={()=>pfRef.current?.click()} className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-gray-50 hover:bg-gray-100 border border-dashed border-gray-300 rounded-xl text-xs text-gray-500">📎 添加 ({pFiles.length}/{MAX_ATT})</button>
                    </div>}
                  </div>}
                </div>

                <button onClick={submitTx} disabled={sync} className="w-full py-3.5 rounded-2xl font-bold text-white active:scale-[0.97] shadow-lg disabled:opacity-60" style={{background:editId?'linear-gradient(135deg,#f59e0b,#ef4444)':'linear-gradient(135deg,#0ea5e9,#6366f1)'}}>{sync?'同步中...':editId?'💾 保存':'✅ 确认录入'}</button>
                {editId&&<button onClick={()=>{setEditId(null);setFd(p=>({...p,price:'',quantity:''}));setProf({...EP});setShowProf(false)}} className="w-full py-2 text-gray-400 hover:text-gray-600 text-sm">取消编辑</button>}
              </div>
            </div></div>

            {/* 列表 */}
            <div className="lg:col-span-2"><div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden flex flex-col" style={{maxHeight:'900px'}}>
              <div className="p-4 border-b border-gray-50 bg-gray-50/50"><span className="font-bold text-gray-700 text-sm">流水列表 ({summary.dayTxs.length})</span></div>
              <div className="overflow-y-auto flex-1">{summary.dayTxs.length===0?<div className="flex flex-col items-center justify-center py-20 text-gray-300"><span className="text-5xl mb-4">📋</span><p className="text-sm">当日暂无记录</p></div>:(<div className="divide-y divide-gray-50">{summary.dayTxs.map((t,i)=>{const at=txAtt[t.id]||[];const ex=expTx===t.id;const hp=!!t.client_name;return(<div key={t.id} className="hover:bg-sky-50/20" style={{animation:`fadeUp 0.3s ease-out ${i*0.04}s both`}}>
                <div className="flex items-center px-4 py-3 gap-3">
                  <span className={`inline-flex items-center px-2.5 py-1 rounded-lg text-[11px] font-bold shrink-0 ${t.type===TxType.BUY?'bg-sky-50 text-sky-600':'bg-amber-50 text-amber-600'}`}>{t.type===TxType.BUY?'📥进货':'📤出货'}</span>
                  <div className="flex-1 min-w-0"><div className="flex items-baseline gap-2 flex-wrap"><span className="text-sm font-semibold text-gray-700">¥{t.price}</span><span className="text-sm text-gray-500">×{fmt(t.quantity)}</span><span className="text-sm text-gray-400">=¥{fmt(t.total)}</span>{hp&&<span className="text-[11px] bg-slate-100 text-slate-600 px-1.5 py-0.5 rounded font-medium">👤{t.client_name}</span>}</div><p className="text-[11px] text-gray-400 mt-0.5">{fmtDate(t.timestamp)} · {t.operator_name}</p></div>
                  <div className="flex items-center gap-1 shrink-0">
                    {(at.length>0||hp)&&<button onClick={()=>setExpTx(ex?null:t.id)} className={`w-8 h-8 rounded-lg flex items-center justify-center transition-all ${ex?'bg-sky-100 text-sky-600':'text-gray-300 hover:text-sky-500 hover:bg-sky-50'}`}><span className="text-sm">{hp?'👤':'📎'}</span></button>}
                    <button onClick={()=>startEdit(t)} disabled={cu?.role===UserRole.OPERATOR&&t.edit_count>=1} className={`w-8 h-8 rounded-lg flex items-center justify-center ${cu?.role===UserRole.OPERATOR&&t.edit_count>=1?'text-gray-200 cursor-not-allowed':'text-gray-300 hover:text-sky-500 hover:bg-sky-50'}`}><svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/></svg></button>
                    {isA&&<button onClick={()=>delTx(t)} className="w-8 h-8 rounded-lg flex items-center justify-center text-gray-300 hover:text-red-500 hover:bg-red-50"><svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg></button>}
                  </div>
                </div>
                {ex&&<div className="px-4 pb-3 space-y-2">{hp&&<ProfileCard t={t}/>}<AttPanel txId={t.id} lid={aLedger.id} atts={at} setAtts={fn=>{const n=typeof fn==='function'?fn(at):fn;setAllAtt(p=>{const f=p.filter(a=>a.transaction_id!==t.id);return[...f,...n]})}} toast={sT} ro={false}/></div>}
                {!ex&&(at.length>0||hp)&&<div className="px-4 pb-2"><span className="text-[10px] text-gray-300">{hp?`👤${t.client_name} `:''}{at.length>0?`📎${at.length}个附件`:''} · 点击查看</span></div>}
              </div>)})}</div>)}</div>
            </div></div>
          </div>
        </div>}

        {tab==='weekly'&&<div className="space-y-6"><h1 className="text-2xl font-extrabold text-gray-900">📈 周度汇总</h1><div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left"><thead className="bg-gray-50/80 border-b border-gray-100"><tr>{['周期','进货(USDT)','进货成本(¥)','出货(USDT)','出货金额(¥)','净利润(¥)'].map(h=><th key={h} className="px-5 py-4 text-[10px] font-bold text-gray-400 uppercase text-right first:text-left">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-50">{weeklyData.length===0?<tr><td colSpan={6} className="px-6 py-16 text-center text-gray-300 text-sm">暂无</td></tr>:weeklyData.map((w,i)=><tr key={w.weekKey} className="hover:bg-sky-50/20" style={{animation:`fadeUp 0.3s ease-out ${i*0.05}s both`}}><td className="px-5 py-4 font-bold text-gray-700 text-sm">{w.weekKey.replace('-W','年第')}周</td><td className="px-5 py-4 text-right text-sm text-sky-600 font-semibold">{fmt(w.buyQty)}</td><td className="px-5 py-4 text-right text-sm text-gray-500">¥{fmt(w.buyAmt)}</td><td className="px-5 py-4 text-right text-sm text-amber-600 font-semibold">{fmt(w.sellQty)}</td><td className="px-5 py-4 text-right text-sm text-gray-500">¥{fmt(w.sellAmt)}</td><td className={`px-5 py-4 text-right text-base font-extrabold ${w.profit>=0?'text-emerald-600':'text-red-600'}`}>{w.profit>=0?'+':''}¥{fmt(w.profit)}</td></tr>)}</tbody>{weeklyData.length>0&&<tfoot className="bg-gray-50 font-bold border-t-2 border-gray-200"><tr><td className="px-5 py-4 text-sm">合计</td><td className="px-5 py-4 text-right text-sky-700 text-sm">{fmt(weeklyData.reduce((a,w)=>a+w.buyQty,0))}</td><td className="px-5 py-4 text-right text-sm">¥{fmt(weeklyData.reduce((a,w)=>a+w.buyAmt,0))}</td><td className="px-5 py-4 text-right text-amber-700 text-sm">{fmt(weeklyData.reduce((a,w)=>a+w.sellQty,0))}</td><td className="px-5 py-4 text-right text-sm">¥{fmt(weeklyData.reduce((a,w)=>a+w.sellAmt,0))}</td>{(()=>{const t=weeklyData.reduce((a,w)=>a+w.profit,0);return<td className={`px-5 py-4 text-right text-lg ${t>=0?'text-emerald-700':'text-red-700'}`}>{t>=0?'+':''}¥{fmt(t)}</td>})()}</tr></tfoot>}</table></div></div></div>}

        {tab==='settings'&&<div className="max-w-2xl mx-auto space-y-6"><h1 className="text-2xl font-extrabold text-gray-900">⚙️ 设置</h1><div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm space-y-4"><h3 className="text-sm font-bold text-gray-400 uppercase">账户</h3><div className="flex items-center gap-4 p-4 bg-gray-50 rounded-2xl"><div className="w-14 h-14 rounded-2xl flex items-center justify-center text-white text-xl font-black" style={{background:'linear-gradient(135deg,#0ea5e9,#6366f1)'}}>{cu.username.slice(0,1).toUpperCase()}</div><div><p className="font-bold text-gray-900 text-lg">{cu.username}</p><p className="text-sky-600 text-sm font-semibold">{isA?'🛡️ 管理员':'👤 操作员'}</p></div></div><div className="grid grid-cols-3 gap-3"><div className="p-4 bg-sky-50 rounded-2xl text-center"><p className="text-2xl font-extrabold text-sky-600">{txs.length}</p><p className="text-xs text-sky-500 mt-1">交易</p></div><div className="p-4 bg-violet-50 rounded-2xl text-center"><p className="text-2xl font-extrabold text-violet-600">{ledgers.length}</p><p className="text-xs text-violet-500 mt-1">交易簿</p></div><div className="p-4 bg-emerald-50 rounded-2xl text-center"><p className="text-2xl font-extrabold text-emerald-600">☁️</p><p className="text-xs text-emerald-500 mt-1">云端</p></div></div></div>{isA&&<div className="bg-white p-6 rounded-2xl border-2 border-red-100 shadow-sm"><h3 className="text-sm font-bold text-red-500 uppercase mb-4">⚠️ 危险</h3><div className="flex flex-col gap-3"><button onClick={()=>setCfm({title:'清空',message:`清空「${aLedger.name}」所有数据？`,onConfirm:async()=>{setSync(true);try{await db.deleteAllTx(aLedger.id);setAllAtt([]);sT('已清空','success')}catch{sT('失败','error')};setSync(false);setCfm(null)},onCancel:()=>setCfm(null)})} className="px-6 py-3 bg-red-500 hover:bg-red-600 text-white rounded-2xl font-bold shadow-lg shadow-red-100">🗑️ 清空当前交易簿</button><button onClick={()=>setCfm({title:'删除',message:`永久删除「${aLedger.name}」？`,onConfirm:async()=>{setSync(true);try{await db.deleteLedger(aLedger.id);setALedger(null);sT('已删除','success')}catch{sT('失败','error')};setSync(false);setCfm(null)},onCancel:()=>setCfm(null)})} className="px-6 py-3 bg-gray-700 hover:bg-gray-800 text-white rounded-2xl font-bold shadow-lg">🔥 删除交易簿</button></div></div>}</div>}
      </main>
      <footer className="bg-white border-t border-gray-100 py-4 text-center text-xs text-gray-300">USDT 管理系统 © {new Date().getFullYear()} — ☁️ 云端同步</footer>
    </div>
  </>)
}
